#library(xts)
if(1)
{
load("RDataTest")

#1
isum=function(x)
{
    if(is.factor(x))
    {
        result=NA
    }else
    {
        result=as.integer(sum(x))
    }
    return(result)
}
#2
imean=function(x)
{
    if(is.factor(x))
    {
        result=NA
    }else
    {
        result=as.integer(mean(x))
        #result=0
    }
    return(result)
}
#3 
rmOutlier2=function(x)
{
    if(is.factor(x))
    {
        result=NA
    }else
    {
        xMorethanZero=x
        xOutlierx=boxplot.stats(xMorethanZero)$out
        #result=as.integer((sum(x)-sum(xOutlierx)+boxplot.stats(xMorethanZero)$stats[5]*NROW(xOutlierx))/NROW(x)+0.085)
        #result=as.integer((sum(x)-sum(xOutlierx)+boxplot.stats(xMorethanZero)$stats[5]*NROW(xOutlierx))/NROW(x))
        #result=(sum(x)-sum(xOutlierx)+boxplot.stats(xMorethanZero)$stats[5]*NROW(xOutlierx))/NROW(x)+0.085
        #result=mean(x,trim=0.2)
        result=(sum(x)-sum(xOutlierx)+boxplot.stats(xMorethanZero)$stats[5]*NROW(xOutlierx))/NROW(x)
    }
    return(result)
}

funl=c(isum,imean,rmOutlier2)

beginDate="2014-07-01"
endDate="2014-12-31"

#
tc=aggregate(t,by=list(t$time),FUN=funl[[1]])
pc=aggregate(p,by=list(p$time),FUN=funl[[1]])
datelist=rbind(tc[1],pc[1])
datelistweek=as.numeric(format(as.Date(datelist[,1]),"%w"))
weekFea=matrix(rep(0,NROW(datelist)*7),NROW(datelist),6)
weekFea[datelistweek==1,1]=1
weekFea[datelistweek==2,2]=1
weekFea[datelistweek==3,3]=1
weekFea[datelistweek==4,4]=1
weekFea[datelistweek==5,5]=1
weekFea[datelistweek==6,6]=1
holidayFea=rep(0,NROW(datelist))
holidayList=c(
              "2014-09-06"
              ,"2014-09-07"
              ,"2014-09-08"
              ,"2014-09-05"

              ,"2014-10-01"
              ,"2014-10-02"
              ,"2014-10-03"
              ,"2014-10-04"
              ,"2014-10-05"
              ,"2014-10-06"
              ,"2014-10-07"
              ,"2014-11-30"

              ,"2015-01-01"
              ,"2015-01-02"
              ,"2015-01-03"
              ,"2014-12-31"
              )
holidayFea[datelist[,1]%in%holidayList]=1
tiaoxiuList=c("2014-09-28","2014-10-11","2015-01-04")
tiaoxiuFea=rep(0,NROW(datelist))
tiaoxiuFea[datelist[,1]%in%tiaoxiuList]=1
dateFea=cbind(weekFea,holidayFea,tiaoxiuFea)


tm<-aggregate(t,by=list(t$uid),FUN=funl[[3]])[,c(1,5:7)]
names(tm)<-c("uid","foreward_count","comment_count","like_count")
ptmp<-p[,1:2]
}
r<-merge(ptmp,tm,by=c("uid"),all.x=T)

if(1)
{
    tu=aggregate(t,by=list(t$uid),FUN=funl[[3]])
    pu=aggregate(p,by=list(p$uid),FUN=funl[[3]])
    totalCount=tu$foreward_count+tu$comment_count+tu$like_count
    tcCut=cut(totalCount,c(-1,0,1,2,3,4,5,10,20,50,100,200,max(totalCount)))
    #tcCut=cut(totalCount,c(-1,0,1,2,3,4,5,6,7,8,9,10,20,50,100,200,max(totalCount)))
    userType=data.frame(uid=tu[,1],userType=tcCut)
    tWithType=merge(t,userType,by="uid",all.x=T)
    pWithType=merge(p,userType,by="uid",all.x=T)
    tt=aggregate(tWithType,by=list(tWithType$time,tWithType$userType),FUN=funl[[3]])
    #
    yvf=NULL
    yvc=NULL
    yvl=NULL
    for(ci in 1:nlevels(tcCut))
    {
        tci=tt[(nlevels(t$time)*(ci-1)+1):(ci*nlevels(t$time)),]
        #submit<-aggregate(tn,by=list(tn$time),FUN=function(x)(NROW(x)))[,5]
        yf=tci[,6]
        fo=boxplot.stats(yf)$out
        yf[yf%in%fo]=boxplot.stats(yf)$stats[5]
        data=data.frame(yf,fea=dateFea[1:NROW(tci),])
        dm=lm(yf~.,data)
        yp=predict(dm,data.frame(fea=dateFea[(NROW(tci)+1):NROW(dateFea),]))
        yvt=data.frame(userType=tci[1,2],time=pc[1],fv=(yp-mean(yf))/mean(yf))
        colnames(yvt)=c("userType","time","fv")
        yvf=rbind(yvf,yvt)

        yc=tci[,7]
        co=boxplot.stats(yc)$out
        yc[yc%in%co]=boxplot.stats(yc)$stats[5]
        data=data.frame(yc,cea=dateFea[1:NROW(tci),])
        dm=lm(yc~.,data)
        yp=predict(dm,data.frame(cea=dateFea[(NROW(tci)+1):NROW(dateFea),]))
        yvt=data.frame(userType=tci[1,2],time=pc[1],cv=(yp-mean(yc))/mean(yc))
        colnames(yvt)=c("userType","time","cv")
        yvc=rbind(yvc,yvt)

        yl=tci[,8]
        lo=boxplot.stats(yl)$out
        yl[yl%in%lo]=boxplot.stats(yl)$stats[5]
        data=data.frame(yl,lea=dateFea[1:NROW(tci),])
        dm=lm(yl~.,data)
        yp=predict(dm,data.frame(lea=dateFea[(NROW(tci)+1):NROW(dateFea),]))
        yvt=data.frame(userType=tci[1,2],time=pc[1],cl=(yp-mean(yl))/mean(yl))
        colnames(yvt)=c("userType","time","lv")
        yvl=rbind(yvl,yvt)

    }
    rme=merge(r,userType,by="uid",all.x=T)
    rme=merge(rme,data.frame(time=p$time,mid=p$mid),by="mid",all.x=T)
    rme=merge(rme,yvf,by=c("userType","time"),all.x=T)
    rme=merge(rme,yvc,by=c("userType","time"),all.x=T)
    rme=merge(rme,yvl,by=c("userType","time"),all.x=T)
    rme$fv[is.na(rme$fv)]=0
    rme$cv[is.na(rme$cv)]=0
    rme$lv[is.na(rme$lv)]=0
    rme$foreward_count=rme$foreward_count*(1+rme$fv)
    rme$comment_count=rme$comment_count*(1+rme$cv)
    rme$like_count=rme$like_count*(1+rme$lv)
    r2=data.frame(rme$uid,rme$mid,rme$foreward_count,rme$comment_count,rme$like_count)
    colnames(r2)<-c("uid","mid","foreward_count","comment_count","like_count")
    r=r2
}

if(0)
{
    yv=matrix(rep(0,NROW(pc)*3),NROW(pc),3)
    for(ci in c(5,6,7))
    {

        y=tc[,ci]
        yo=boxplot.stats(y)$out
        y[y%in%yo]=boxplot.stats(y)$stats[5]
        data=data.frame(y,fea=dateFea[1:NROW(tc),])
        dm=lm(y~.,data)
        yf=predict(dm,data.frame(fea=dateFea[(1+NROW(tc)):NROW(dateFea),]))
        yv[,ci-4]=(yf-mean(y))/mean(y)
    }
    yv=cbind(yv,pc[1])
    colnames(yv)=c("fv","cv","lv","time")
    rme=merge(r,data.frame(time=p$time,mid=p$mid),by="mid",all.x=T)
    rme=merge(rme,yv,by=c("time"),all.x=T)
    rme$foreward_count=rme$foreward_count*(1+rme$fv)
    rme$comment_count=rme$comment_count*(1+rme$cv)
    rme$like_count=rme$like_count*(1+rme$lv)
    r3=data.frame(rme$uid,rme$mid,rme$foreward_count,rme$comment_count,rme$like_count)
    colnames(r3)<-c("uid","mid","foreward_count","comment_count","like_count")
    r=r3
}

#tm1<-aggregate(tn,by=list(tn$time),FUN=funl[[2]])
#
#tm15<-xts(tm1[5],seq(as.POSIXct(beginDate),len=NROW(tm1),by='day'))
#tm16<-xts(tm1[6],seq(as.POSIXct(beginDate),len=NROW(tm1),by='day'))
#tm17<-xts(tm1[7],seq(as.POSIXct(beginDate),len=NROW(tm1),by='day'))
#tm55<-xts(tm5[5],seq(as.POSIXct(beginDate),len=NROW(tm5),by='day'))
#plot(as.zoo(cbind(tm15,tm16,tm17)),col=c(2:6,8,9),lty=2:9,screens=1)
#legend(x="topleft",legend=c("foreward_count","comment_count","like_count"),col=c(2:6,8,9),lty=2:9)
#plot(tm15,main="foreward_count")
#plot(tm16,main="comment_count")
#plot(tm17,main="like_count")
#plot(tm55,main="submit_count")
#r$foreward_count=round(r$foreward_count*(yv[1]))
#r$comment_count=round(r$comment_count*(yv[2]))
#r$like_count=round(r$like_count*(yv[3]))
#r$foreward_count=as.integer(r$foreward_count*yv[1])
#r$comment_count=as.integer(r$comment_count*yv[2])
#r$like_count=as.integer(r$like_count*yv[3])
#r$foreward_count=as.integer(r$foreward_count)
#r$comment_count=as.integer(r$comment_count)
#r$like_count=as.integer(r$like_count)
#r$foreward_count=round(r$foreward_count)
#r$comment_count=round(r$comment_count)
#r$like_count=round(r$like_count)

r$foreward_count[is.na(r$foreward_count)]=0
r$comment_count[is.na(r$comment_count)]=0
r$like_count[is.na(r$like_count)]=0
if(1)
{
    rp<-merge(p,r,by=c("uid","mid"))
    devf=abs(rp$foreward_count.y-rp$foreward_count.x)/(rp$foreward_count.x+5)
    devc=abs(rp$comment_count.y-rp$comment_count.x)/(rp$comment_count.x+3)
    devl=abs(rp$like_count.y-rp$like_count.x)/(rp$like_count.x+3)
    prei=1-0.5*devf-0.25*devc-0.25*devl
    pret=prei
    prei[(prei-0.8)>0]=1
    prei[(prei-0.8)<=0]=0
    count=(rp$foreward_count.x+rp$comment_count.x+rp$like_count.x)
    count[count>100]=100
    pre=sum((count+1)*prei)/sum(count+1)
    #print(Sys.time())
    cat(">>> precision  = ",pre,"\n")
    #print(Sys.time())
}
